//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesiana.Cloud.Client.Salesiana_Cloud_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Salesiana_Cloud_Service.ITransferService")]
    public interface ITransferService {
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadRequest) of message DownloadRequest does not match the default value (DownloadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferService/DownloadFile", ReplyAction="http://tempuri.org/ITransferService/DownloadFileResponse")]
        Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo DownloadFile(Salesiana.Cloud.Client.Salesiana_Cloud_Service.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferService/DownloadFile", ReplyAction="http://tempuri.org/ITransferService/DownloadFileResponse")]
        System.Threading.Tasks.Task<Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo> DownloadFileAsync(Salesiana.Cloud.Client.Salesiana_Cloud_Service.DownloadRequest request);
        
        // CODEGEN: Generating message contract since the operation UploadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferService/UploadFile", ReplyAction="http://tempuri.org/ITransferService/UploadFileResponse")]
        Salesiana.Cloud.Client.Salesiana_Cloud_Service.UploadFileResponse UploadFile(Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferService/UploadFile", ReplyAction="http://tempuri.org/ITransferService/UploadFileResponse")]
        System.Threading.Tasks.Task<Salesiana.Cloud.Client.Salesiana_Cloud_Service.UploadFileResponse> UploadFileAsync(Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FileName;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string FileName) {
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(string FileName, long Length, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransferServiceChannel : Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransferServiceClient : System.ServiceModel.ClientBase<Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService>, Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService {
        
        public TransferServiceClient() {
        }
        
        public TransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService.DownloadFile(Salesiana.Cloud.Client.Salesiana_Cloud_Service.DownloadRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public long DownloadFile(ref string FileName, out System.IO.Stream FileByteStream) {
            Salesiana.Cloud.Client.Salesiana_Cloud_Service.DownloadRequest inValue = new Salesiana.Cloud.Client.Salesiana_Cloud_Service.DownloadRequest();
            inValue.FileName = FileName;
            Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo retVal = ((Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService)(this)).DownloadFile(inValue);
            FileName = retVal.FileName;
            FileByteStream = retVal.FileByteStream;
            return retVal.Length;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo> Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService.DownloadFileAsync(Salesiana.Cloud.Client.Salesiana_Cloud_Service.DownloadRequest request) {
            return base.Channel.DownloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo> DownloadFileAsync(string FileName) {
            Salesiana.Cloud.Client.Salesiana_Cloud_Service.DownloadRequest inValue = new Salesiana.Cloud.Client.Salesiana_Cloud_Service.DownloadRequest();
            inValue.FileName = FileName;
            return ((Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService)(this)).DownloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Salesiana.Cloud.Client.Salesiana_Cloud_Service.UploadFileResponse Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService.UploadFile(Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string FileName, long Length, System.IO.Stream FileByteStream) {
            Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo inValue = new Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            Salesiana.Cloud.Client.Salesiana_Cloud_Service.UploadFileResponse retVal = ((Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Salesiana.Cloud.Client.Salesiana_Cloud_Service.UploadFileResponse> Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService.UploadFileAsync(Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Salesiana.Cloud.Client.Salesiana_Cloud_Service.UploadFileResponse> UploadFileAsync(string FileName, long Length, System.IO.Stream FileByteStream) {
            Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo inValue = new Salesiana.Cloud.Client.Salesiana_Cloud_Service.RemoteFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((Salesiana.Cloud.Client.Salesiana_Cloud_Service.ITransferService)(this)).UploadFileAsync(inValue);
        }
    }
}
